services:
  nats_server:
    image: nats:2.9.8
    ports:
      - 8222:8222

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats_server:4222

  products-ms:
    build:
      context: ./products-ms
      dockerfile: Dockerfile
    volumes:
      - ./products-ms/src:/usr/src/app/src
      - ./products-ms/prisma:/usr/src/app/prisma
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats_server:4222
      - DATABASE_URL=file:/usr/src/app/dev.db

  orders-db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: alejandro
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alejandro -d ordersdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  orders-ms:
    depends_on:
      orders-db:
        condition: service_healthy
    build:
      context: ./orders-ms
      dockerfile: Dockerfile
    volumes:
      - ./orders-ms/src:/usr/src/app/src
      - ./orders-ms/prisma:/usr/src/app/prisma
    command: npm run start:dev
    environment:
      - NATS_SERVERS=nats://nats_server:4222
      - DATABASE_URL=postgresql://alejandro:postgres@orders-db:5432/ordersdb

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: Dockerfile
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats_server:4222
      - STRIPE_SECRET_END_POINT_KEY=${STRIPE_SECRET_END_POINT_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}

  auth-ms:
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=nats://nats_server:4222
      - DATABASE_URL=${MONGODB_URL}
      - DATABASE=users